/*
 * Copyright (C) 2026 GreenWaves Technologies
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* @file    devicetree_internal.h
 * @brief   C formatted devicetree content
 *
 * This file has been generated from the devicetree (*.dts files) and enabled
 * Kconfig options. It defines availables features from the board you are using
 *
 * @note This file is automatically generated during the project configuration
 *       Do not edit it.
 */

#pragma once
#include <pi_device.h>

// cluster *********************************************************************

#include "pmsis/cluster/cl_pmsis_types.h"

extern pi_device_t cluster_dev;

// mx25u51245g *****************************************************************

#include "mx25u51245g.h"

extern pi_device_t mx25u51245g_dev;

// mram ************************************************************************

#include "mram.h"

extern pi_device_t mram_dev;

// periph3v3 *******************************************************************

#include "powersupplygpio.h"

extern pi_device_t periph3v3_dev;

// cam3v3 **********************************************************************

#include "powersupplygpio.h"

extern pi_device_t cam3v3_dev;

// aps256xxn *******************************************************************

#include "aps256xxn.h"

extern pi_device_t aps256xxn_dev;

// Devices pointers ************************************************************

#define DEVICE_PTR_CORE_CLUSTER          &cluster_dev
#define DEVICE_PTR_FLASH_MX25U51245G     &mx25u51245g_dev
#define DEVICE_PTR_FLASH_MRAM            &mram_dev
#define DEVICE_PTR_POWERSUPPLY_PERIPH3V3 &periph3v3_dev
#define DEVICE_PTR_POWERSUPPLY_CAM3V3    &cam3v3_dev
#define DEVICE_PTR_RAM_APS256XXN         &aps256xxn_dev

#define DEVICE_PTR_FLASH_DEFAULT         DEVICE_PTR_FLASH_MX25U51245G
#define DEVICE_PTR_RAM_DEFAULT           DEVICE_PTR_RAM_APS256XXN

