/*
 * Copyright (C) 2026 GreenWaves Technologies
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* @file    dt.h
 * @brief   C formatted devicetree content
 *
 * This file has been generated from the devicetree (*.dts files) and enabled
 * Kconfig options. It defines availables features from the board you are using
 *
 * @note This file is automatically generated during the project configuration
 *       Do not edit it.
 */

#pragma once
#include <stdint.h>
#include <pi_device.h>
#include <devicetree_internal.h>

// cluster *********************************************************************

#define DT_CLUSTER_ID            (0)
#define DT_CLUSTER_CC_STACK_SIZE (0x800)
#define DT_CLUSTER_SCRATCH_SIZE  (0x00)
#define DT_CLUSTER_ICACHE_CONF   (0x7FF)
#define DT_CLUSTER_FLAGS         (0)

#define PI_CORE_CLUSTER_ID (0x499f248e)

// mx25u51245g *****************************************************************

#define DT_MX25U51245G_BAUDRATE    (200000000)
#define DT_MX25U51245G_XIP_EN      (0)
#define DT_MX25U51245G_SECTOR_SIZE (4096)
#define DT_MX25U51245G_SIZE        (67108864)
#define DT_MX25U51245G_SPI_CS      (0)
#define DT_MX25U51245G_SPI_ITF     (0)

#define PI_FLASH_MX25U51245G_ID (0x0853f9fe)

// mram ************************************************************************

#define DT_MRAM_ITF      (0)
#define DT_MRAM_BAUDRATE (34000000)
#define DT_MRAM_XIP_EN   (0)

#define PI_FLASH_MRAM_ID (0x7abf5849)

// periph3v3 *******************************************************************

#define DT_PERIPH3V3_PAD_ID (35)

#define PI_POWERSUPPLY_PERIPH3V3_ID (0xb16a4f45)

// cam3v3 **********************************************************************

#define DT_CAM3V3_PAD_ID (0)

#define PI_POWERSUPPLY_CAM3V3_ID (0x8cf2f20c)

// aps256xxn *******************************************************************

#define DT_APS256XXN_RAM_AES_CONF_QK_EN   (0)
#define DT_APS256XXN_RAM_AES_CONF_ENABLED (0)
#define DT_APS256XXN_MBA                  (33554432)
#define DT_APS256XXN_RESERVE_ADDR_0       (1)
#define DT_APS256XXN_XIP_EN               (0)
#define DT_APS256XXN_BAUDRATE             (200000000)
#define DT_APS256XXN_RAM_SIZE             (33554432)
#define DT_APS256XXN_RAM_START            (0)
#define DT_APS256XXN_SPI_CS               (1)
#define DT_APS256XXN_SPI_ITF              (0)

#define PI_RAM_APS256XXN_ID (0xf4815cce)

// Devices enum ****************************************************************

typedef enum {
    PI_CORE_CLUSTER          = PI_CORE_CLUSTER_ID,
    PI_FLASH_MX25U51245G     = PI_FLASH_MX25U51245G_ID,
    PI_FLASH_DEFAULT,
    PI_FLASH_MRAM            = PI_FLASH_MRAM_ID,
    PI_POWERSUPPLY_PERIPH3V3 = PI_POWERSUPPLY_PERIPH3V3_ID,
    PI_POWERSUPPLY_CAM3V3    = PI_POWERSUPPLY_CAM3V3_ID,
    PI_RAM_APS256XXN         = PI_RAM_APS256XXN_ID,
    PI_RAM_DEFAULT,
}pi_device_e;
// Devices API *****************************************************************

int32_t pi_open(pi_device_e device_enum, pi_device_t** device_ptr);

int32_t pi_close(pi_device_e device_enum);

// Padfun registers ************************************************************

#define PADFUN0_INIT (0x54000001)
#define PADFUN1_INIT (0x55555555)
#define PADFUN2_INIT (0x55555555)
#define PADFUN3_INIT (0x55555555)
#define PADFUN4_INIT (0x55555555)
#define PADFUN5_INIT (0x55555001)

// Reprog registers ************************************************************

#define REPROG0_INIT (0x040C2040)
#define REPROG1_INIT (0x0C289206)
#define REPROG2_INIT (0x144D240E)
#define REPROG3_INIT (0x2179B616)

// Pads define *****************************************************************

#define PAD_MX25U51245G_RWDS (PI_PAD_012)
#define PAD_MX25U51245G_CSN1 (PI_PAD_011)
#define PAD_MX25U51245G_SN0  (PI_PAD_010)
#define PAD_MX25U51245G_DQ7  (PI_PAD_009)
#define PAD_MX25U51245G_DQ6  (PI_PAD_008)
#define PAD_MX25U51245G_DQ5  (PI_PAD_007)
#define PAD_MX25U51245G_DQ4  (PI_PAD_006)
#define PAD_MX25U51245G_DQ3  (PI_PAD_005)
#define PAD_MX25U51245G_DQ2  (PI_PAD_004)
#define PAD_MX25U51245G_DQ1  (PI_PAD_003)
#define PAD_MX25U51245G_DQ0  (PI_PAD_002)
#define PAD_MX25U51245G_CK   (PI_PAD_001)
#define PAD_APS256XXN_RWDS   (PI_PAD_012)
#define PAD_APS256XXN_CSN1   (PI_PAD_011)
#define PAD_APS256XXN_SN0    (PI_PAD_010)
#define PAD_APS256XXN_DQ7    (PI_PAD_009)
#define PAD_APS256XXN_DQ6    (PI_PAD_008)
#define PAD_APS256XXN_DQ5    (PI_PAD_007)
#define PAD_APS256XXN_DQ4    (PI_PAD_006)
#define PAD_APS256XXN_DQ3    (PI_PAD_005)
#define PAD_APS256XXN_DQ2    (PI_PAD_004)
#define PAD_APS256XXN_DQ1    (PI_PAD_003)
#define PAD_APS256XXN_DQ0    (PI_PAD_002)
#define PAD_APS256XXN_CK     (PI_PAD_001)
#define PAD_JTAG_TRST        (PI_PAD_085)
#define PAD_JTAG_TMS         (PI_PAD_084)
#define PAD_JTAG_TDO         (PI_PAD_083)
#define PAD_JTAG_TDI         (PI_PAD_082)
#define PAD_JTAG_TCK         (PI_PAD_081)

