/*
 * Copyright (C) 2026 GreenWaves Technologies
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* @file    dt.c
 * @brief   C formatted devicetree content
 *
 * This file has been generated from the devicetree (*.dts files) and enabled
 * Kconfig options. It defines availables features from the board you are using
 *
 * @note This file is automatically generated during the project configuration
 *       Do not edit it.
 */

#include <dt.h>
#include <devicetree_internal.h>

// Devices API *****************************************************************

int32_t pi_open(pi_device_e device_enum, pi_device_t** device_ptr)
{
    int32_t err = 0;
    switch (device_enum)
    {
        case PI_CORE_CLUSTER:
        {
           *device_ptr = DEVICE_PTR_CORE_CLUSTER;
           break;
        }
        case PI_FLASH_MX25U51245G:
        case PI_FLASH_DEFAULT :
        {
           *device_ptr = DEVICE_PTR_FLASH_MX25U51245G;
           break;
        }
        case PI_FLASH_MRAM:
        {
           *device_ptr = DEVICE_PTR_FLASH_MRAM;
           break;
        }
        case PI_POWERSUPPLY_PERIPH3V3:
        {
           *device_ptr = DEVICE_PTR_POWERSUPPLY_PERIPH3V3;
           break;
        }
        case PI_POWERSUPPLY_CAM3V3:
        {
           *device_ptr = DEVICE_PTR_POWERSUPPLY_CAM3V3;
           break;
        }
        case PI_RAM_APS256XXN:
        case PI_RAM_DEFAULT :
        {
           *device_ptr = DEVICE_PTR_RAM_APS256XXN;
           break;
        }
        default:
        {
            err = -1;
            break;
        }
    }
    if ((device_ptr != NULL) && (err == 0))
    {
        err = (*device_ptr)->api->open(*device_ptr);
    }
    return err;
}

int32_t pi_close(pi_device_e device_enum)
{
    int32_t err = 0;
    pi_device_t* device_ptr = NULL;
    switch (device_enum)
    {
        case PI_CORE_CLUSTER:
        {
            device_ptr = DEVICE_PTR_CORE_CLUSTER;
            break;
        }
        case PI_FLASH_MX25U51245G:
        case PI_FLASH_DEFAULT:
        {
            device_ptr = DEVICE_PTR_FLASH_MX25U51245G;
            break;
        }
        case PI_FLASH_MRAM:
        {
            device_ptr = DEVICE_PTR_FLASH_MRAM;
            break;
        }
        case PI_POWERSUPPLY_PERIPH3V3:
        {
            device_ptr = DEVICE_PTR_POWERSUPPLY_PERIPH3V3;
            break;
        }
        case PI_POWERSUPPLY_CAM3V3:
        {
            device_ptr = DEVICE_PTR_POWERSUPPLY_CAM3V3;
            break;
        }
        case PI_RAM_APS256XXN:
        case PI_RAM_DEFAULT:
        {
            device_ptr = DEVICE_PTR_RAM_APS256XXN;
            break;
        }
        default:
        {
            err = -1;
            break;
        }
    }
    if ((device_ptr != NULL) && (err == 0))
    {
        err = (device_ptr)->api->close(device_ptr);
    }
    return err;
}

